import React, { useState, useEffect } from 'react';
import { exec, toast } from 'kernelsu';
import './App.css';

interface CSCEntry {
  command: 'MODIFY' | 'DELETE';
  key: string;
  value: string;
}

const FILE_LIST = [
  { label: 'Carrier', name: 'ml_carrier.txt' },
  { label: 'CSC', name: 'ml_csc.txt' },
  { label: 'FF', name: 'ml_ff.txt' },
];

const BASE_PATH = "/data/adb/modules/auto_modify_cscfeature/";

export const App: React.FC = () => {
  const [currentFile, setCurrentFile] = useState(FILE_LIST[0].name);
  const [entries, setEntries] = useState<CSCEntry[]>([]);
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);

  const [formData, setFormData] = useState<CSCEntry>({ command: 'MODIFY', key: '', value: '' });

  useEffect(() => {
    loadFile(currentFile);
  }, [currentFile]);

  const loadFile = async (fileName: string) => {
    setLoading(true);
    setStatus(`正在读取 ${fileName}...`);
    
    let path = `${BASE_PATH}${fileName}`;
    let res = await exec(`[ -f ${path} ] && cat ${path}`);
    
    if (res.errno !== 0 || !res.stdout) {
      path = `${BASE_PATH}${fileName}.example`;
      res = await exec(`[ -f ${path} ] && cat ${path}`);
    }

    if (res.errno === 0 && res.stdout) {
      const parsed = res.stdout.split(/\r?\n/)
        .map(line => line.trim())
        .filter(line => line && !line.startsWith('#'))
        .map(line => {
          const parts = line.split('|');
          const cmd = parts[0] === 'DELETE' ? 'DELETE' : 'MODIFY';
          const key = parts[1] || '';
          const value = parts[2] || '';
          return { command: cmd, key, value } as CSCEntry;
        });
      setEntries(parsed);
      setStatus(`已加载: ${path}`);
    } else {
      setEntries([]);
      setStatus('未找到文件或文件为空，请点击添加开始。');
    }
    setLoading(false);
  };

  const handleSave = async () => {
    setLoading(true);
    const lines = [
      "# Generated by KSU WebUI",
      "",
      ...entries.map(e => e.command === 'DELETE' ? `DELETE|${e.key}` : `MODIFY|${e.key}|${e.value}`)
    ];
    const content = lines.join('\n') + '\n';

    const target = `${BASE_PATH}${currentFile}`;
    const temp = `/data/local/tmp/csc_temp.txt`;

    try {
      const res1 = await exec(`echo '${content.replace(/'/g, "'\\''")}' > ${temp}`);
      if (res1.errno !== 0) throw new Error(res1.stderr);
      
      const res2 = await exec(`cp ${temp} ${target} && chmod 644 ${target} && rm ${temp}`);
      if (res2.errno !== 0) throw new Error(res2.stderr);

      setStatus(`已保存至 ${target}`);
      toast('保存成功！');
    } catch (e: any) {
      toast(`保存失败: ${e.message}`);
    }
    setLoading(false);
  };

  const openModal = (index: number | null = null) => {
    if (index !== null) {
      setFormData({ ...entries[index] });
      setEditingIndex(index);
    } else {
      setFormData({ command: 'MODIFY', key: '', value: '' });
      setEditingIndex(null);
    }
    setIsModalOpen(true);
  };

  const saveEntry = () => {
    if (!formData.key) {
        toast('键名不能为空');
        return;
    }
    const newEntries = [...entries];
    if (editingIndex !== null) {
      newEntries[editingIndex] = formData;
    } else {
      newEntries.push(formData);
    }
    setEntries(newEntries);
    setIsModalOpen(false);
  };

  const removeEntry = (index: number) => {
    if (confirm('确定删除此项吗？')) {
      const newEntries = [...entries];
      newEntries.splice(index, 1);
      setEntries(newEntries);
    }
  };

  return (
    <div className="container">
      <header>
        <h1>CSC Editor</h1>
        <div className="tabs">
          {FILE_LIST.map(f => (
            <button 
              key={f.name}
              className={currentFile === f.name ? 'active' : ''}
              onClick={() => setCurrentFile(f.name)}
            >
              {f.label}
            </button>
          ))}
        </div>
      </header>

      <div className="status">{status}</div>

      <div className="actions">
        <button className="btn primary" onClick={() => openModal()}>添加配置</button>
        <button className="btn success" onClick={handleSave} disabled={loading}>保存全部</button>
      </div>

      <div className="list">
        {entries.map((entry, i) => (
          <div key={i} className="item">
            <div className="info">
              <div className="key">{entry.key}</div>
              <div className="meta">{entry.command} {entry.value && `| ${entry.value}`}</div>
            </div>
            <div className="btns">
              <button onClick={() => openModal(i)}>✎</button>
              <button onClick={() => removeEntry(i)}>🗑</button>
            </div>
          </div>
        ))}
      </div>

      {isModalOpen && (
        <div className="modal">
          <div className="modal-content">
            <h3>{editingIndex !== null ? '编辑' : '添加'}配置</h3>
            <select 
              value={formData.command} 
              onChange={e => setFormData({...formData, command: e.target.value as any})}
            >
              <option value="MODIFY">MODIFY</option>
              <option value="DELETE">DELETE</option>
            </select>
            <input 
              placeholder="键名 (Key)"
              value={formData.key}
              onChange={e => setFormData({...formData, key: e.target.value})}
            />
            {formData.command === 'MODIFY' && (
              <input 
                placeholder="键值 (Value)"
                value={formData.value}
                onChange={e => setFormData({...formData, value: e.target.value})}
              />
            )}
            <div className="modal-btns">
              <button onClick={() => setIsModalOpen(false)}>取消</button>
              <button className="primary" onClick={saveEntry}>确定</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
